experiment:
  ckpt: sentence-transformers/paraphrase-MiniLM-L3-v2
  dataset: hate-speech # can be 'analyse-tal', 'hate-speech', 'sentiment', 'ten-dim'
  use_augmented_data: False
  wandb_project: ten_social_dim
  wandb_entity: cocoons

multilabel_params:
  batch_size: 32
  lr: 2e-5
  num_epochs: 5
  weight_decay: 0
  ckpt: ${experiment.ckpt}
  wandb_project: ${experiment.wandb_project}
  wandb_entity: ${experiment.wandb_entity}
